version: "3.9"
services:
  screenshots:
    build: .
    ports:
      - "5010:5010"
    environment:
      - EMAIL_FACEBOOK=
      - PASSWORD_FACEBOOK=
      - EMAIL_INSTAGRAM=
      - PASSWORD_INSTAGRAM=
    volumes:
      - ./app/data_chrome:/usr/src/app/data_chrome